{
 "title": "Kafka Connect Overview-0",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_connect_commit_id_info,instance)"
    }
   },
   {
    "name": "connector",
    "query": {
     "query": "label_values(kafka_connect_connector_task_pause_ratio,connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "graph",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "graph",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  { "title": "Connect Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Connect Worker",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kafka_connect_app_info{instance=~\"$instance\",start_time_ms!=\"\"}"
    },
    {
     "expr": "kafka_connect_app_info{instance=~\"$instance\",version!=\"\"}"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_connector_count{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_connector_startup_success_total{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_connector_startup_failure_total{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_task_count{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_task_startup_success_total{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_task_startup_failure_total{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Connector details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Connectors",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    },
    {
     "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",connector_type!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_total_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "graph",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_connect_source_task_source_record_poll_total{instance=~\"$instance\",connector=~\"$connector\"}[1m])",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write rate",
   "type": "graph",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_connect_source_task_source_record_write_total{instance=~\"$instance\",connector=~\"$connector\"}[1m])",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Size Average",
   "type": "graph",
   "description": "Record size Average",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{clientId=\"connector-producer-postgres-source-0\",instance=\"kafka-connect:9876\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "graph",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg{instance=\"kafka-connect:9876\",task=\"0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Per Request Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg{clientId=\"connector-producer-postgres-source-0\",instance=\"kafka-connect:9876\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Send AVG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "item" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_topic_record_send_total{clientId=\"connector-producer-postgres-source-0\",instance=\"kafka-connect:9876\",topic=\"postgresql-jdbc-bulk-users\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Send Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{instance=\"kafka-connect:9876\",task=\"0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}